# Generated by Django 6.0.3 on 2026-03-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa do Veículo')),
                ('categoria', models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('CAMINHAO', 'Caminhão')], max_length=10, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Cobrado')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data da Passagem')),
            ],
            options={
                'verbose_name': 'Passagem',
                'verbose_name_plural': 'Passagens',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True, verbose_name='TXID')),
                ('payload', models.TextField(verbose_name='PIX Copia e Cola')),
                ('qr_code_base64', models.TextField(verbose_name='QR Code (Base64)')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('pago', models.BooleanField(default=False, verbose_name='Pagamento Confirmado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('passagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix', to='tolls.passagem', verbose_name='Passagem Referência')),
            ],
            options={
                'verbose_name': 'Cobrança PIX',
                'verbose_name_plural': 'Cobranças PIX',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
