# Generated by Django 6.0.3 on 2026-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatarifa',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição (Ex: Passeio)'),
        ),
    ]
